services:
  # Основной сервис
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    restart: always
    command: redis-server --appendonly yes #  включает режим RDB/AOF для сохранения данных на диск
    volumes:
      - redis_data:/data

  app:
    build: .
    container_name: backend
    restart: on-failure:5
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    env_file:
      - .env
    environment:
      TZ: Europe/Moscow


volumes:
  postgres_data:
  redis_data:

networks:
  postgres_network:
    driver: bridge
    internal: false