services:
  # Основной сервис
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  app:
    build: .
    container_name: backend
    restart: on-failure:5
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    env_file:
      - .env
    environment:
      TZ: Europe/Moscow


volumes:
  postgres_data:

networks:
  postgres_network:
    driver: bridge
    internal: false